# Generated by Django 4.1.10 on 2023-08-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
    ]
