# Generated by Django 4.1.10 on 2023-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_people_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='availability',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='location',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
